apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-devops-java
spec:
  selector:
    matchLabels:
      app: demo-devops-java
  template:
    metadata:
      labels:
        app: demo-devops-java
    spec:
      containers:
      - name: demo-devops-java
        image: "gaparedes/devsu"
        ports:
        - containerPort: 8000
          protocol: TCP
        - containerPort: 80
          protocol: TCP


---

apiVersion: v1
kind: Service
metadata:
  name: demo-devops-java-svc
spec:
  selector:
    app: demo-devops-java
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-devops-java-ingress
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway

spec:
  rules:
  - host: 13.68.243.235
  - http:
      paths:
      - path: /api
        backend:
          service:
            name: demo-devops-java-svc
            port:
              number: 80
        pathType: Prefix


